---
- name: check for required fact ansible_network_os
  fail:
    msg: "missing required fact: ansible_network_os"
  when: ansible_network_os is undefined

- name: include and run device provider specific tasks
  include_tasks: provider.yaml
